spring:
  profiles:
    active: dev

# Swagger界面内容配置
swagger:
  title: spring-boot-ftp-sftp API接口文档
  description: spring-boot-ftp-sftp Api Documentation
  version: 1.0.0
  show: true
  contact:
    name: wulinyun
    url:
    email: lin.wu@landasoft.com