spring:
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 192.168.223.133 #Redis服务器地址
    port: 16379 #Redis服务器连接端口
    password: 123456 #Redis服务器连接密码（默认为空）
    timeout: 6000 #连接超时时间（毫秒）
    #集群环境打开下面注释，单机不需要打开
    #    cluster:
    #      集群信息
    #      nodes: xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx
    #      #默认值是5 一般当此值设置过大时，容易报：Too many Cluster redirections
    #      maxRedirects: 3
    jedis:
      pool:
        max-active: 200 #连接池最大连接数（使用负值表示没有限制）        max-idle: 10 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 #连接池中的最小空闲连接
