server:
  port: 8080
spring:
  application:
    name: spring-boot-demo-rabbitmq-sender
  rabbitmq:
    host: 10.163.4.121
    port: 5672
    username: guest
    password: guest
    virtual-host: / #没有特别设置另外的默认是/
