server:
  port: 9002
#数据源配置
spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch-cluster
      cluster-nodes: 192.168.223.133:9300
      repositories:
        enabled: true
logging:
  level:
    com.landasoft.demo: debug
