eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:127.0.0.1}:8761/eureka/
  instance:
#    hostname: localhost
    prefer-ip-address: true
logging:
  level:
    com:
      landasoft:
        demo:
          springcloud: info
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.landasoft.demo.springcloud.springcloudseatastorageserver.entity
server:
  port: 8182
spring:
  application:
    name: storage-server
  cloud:
    alibaba:
      seata:
        tx-service-group: fsp_tx_group
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    url: jdbc:mysql://192.168.223.133/seat-storage
    username: root
