server:
  port: 11021
spring:
  application:
    name: landa-mas-zipkin-stream-client
  profiles:
    active: dev #@spring.profiles.active@
# Swagger界面内容配置
swagger:
  title: landa-mas-zipkin-stream-client API接口文档
  description: landa-mas-zipkin-stream-client Api Documentation
  version: 1.0.0
  show: true
  contact:
    name: wulinyun
    url:
    email: lin.wu@landasoft.com