server:
  port: 8080
  #程序增加SSL证书
  ssl:
    key-store: classpath:pgiff.keystore #生成方法可参考https://blog.51cto.com/xuanxy/2388551
    key-store-password: iffadmin
    key-store-type: JKS
    key-alias: pgiff
demo:
  msg: "hello dev update!"