server:
  port: 8080
  #程序增加SSL证书
#  ssl:
#    key-store: classpath:pgiff.keystore #生成方法可参考https://blog.51cto.com/xuanxy/2388551
#    key-store-password: iffadmin
#    key-store-type: JKS
#    key-alias: pgiff
demo:
  msg: "hello dev update!"

## cloud
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:127.0.0.1}:8761/eureka/ #spring-cloud-discovery
  instance:
    prefer-ip-address: true