server:
  port: 8080
spring:
  application:
    name: spring-cloud-hystrix-turbine
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:127.0.0.1}:8761/eureka/
  instance:
    prefer-ip-address: true

turbine:
  #appConfig 配置Eureka中的serviceId列表，表明监控哪些服务，多个服务id用 ， 逗号隔开
  app-config: spring-cloud-hystrix-dashboard,spring-cloud-hystrix
  aggregator:
    cluster-config: default
  cluster-name-expression: new String("default")
