server:
  port: 11009
spring:
  application:
    name: landa-mas-zipkin-client
  zipkin:
    base-url: http://localhost:11008 #http
#    base-url: http://spring-cloud-tracing:9411 #http

  sleuth:
      web:
        client:
          enabled: true
      sampler:
        probability: 1.0 # 采用比例，默认 0.1 全部采样 1.0
