server:
  port: 8081
spring:
  application:
    name: spring-boot-demo-rabbitmq-receiver
  rabbitmq:
    host: 192.168.223.133
    port: 5672
    username: guest
    password: guest
    virtual-host: /landa_demo #没有特别设置另外的默认是/

