server:
  port: 8002
spring:
  application:
    name: spring-cloud-config-client
  cloud:
    config:
      name: easy-config
      profile: dev
      uri: http://localhost:8001/ #配置中心的具体地址(sever端地址)
      label: master #对应git的分支。如果配置中心使用的是本地存储，则该参数无用
      discovery:
        enabled: true
        service-id: spring-cloud-config-server

  #rabbitmq的配置
  rabbitmq:
    host: 192.168.223.133
    port: 5672
    username: guest
    password: guest

#注册中心配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



