server:
  port: 8002
spring:
  #rabbitmq的配置
  rabbitmq:
    host: 192.168.223.133
    port: 5672
    username: guest
    password: guest

#注册中心配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



