server:
  port: 8082
spring:
  application:
    name: spring-cloud-hystrix
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:127.0.0.1}:8761/eureka/
  instance:
    prefer-ip-address: true
