spring:
  cloud:
    config:
      server:
        git:
          # 配置文件只搜索url目录下的searchPaths
          uri: https://github.com/wulinyun/spring-cloud-demo.git
          username:   # git仓库的账号
          password:   # git仓库的密码
          # 指定搜索路径，如果有多个路径则使用,分隔
          search-paths: /spring-cloud-configs/configs-repo/
          # 对于使用git,svn做为后端配置，从远程库获取配置文件，需要存储到本地文件
          basedir: /tmp/spring-cloud-repo
          # 配置中心通过git从远程git库，有时本地的拷贝被污染，这时配置中心无法从远程库更新本地配置,设置force-pull=true，则强制从远程库中更新本地库
          force-pull: true
  rabbitmq:
    host: 192.168.223.133
    port: 5672
    username: guest
    password: guest
#注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
