server:
  port: 8001
spring:
  application:
    name: spring-cloud-configs-server
  profiles:
    active: native,dev #test
#暴露actuator端点 手动模拟测试配置文件刷新  http://localhost:8001/actuator/bus-refresh
management:
  endpoints:
    web:
      exposure:
        include: "*"
        #include: "bus-refresh"